name: Sync Wrike and Confluence

# 5분마다 실행
on:
  schedule:
    - cron: '0/5 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      
      - name: Install dependencies
        run: go mod tidy

      - name: Run main.go
        env:
          CONFLUENCE_DOMAIN: ${{ secrets.CONFLUENCE_DOMAIN }}
          CONFLUENCE_USER: ${{ secrets.CONFLUENCE_USER }}
          CONFLUENCE_TOKEN: ${{ secrets.CONFLUENCE_TOKEN }}
          CONFLUENCE_SPACEID: ${{ secrets.CONFLUENCE_SPACEID }}
          CONFLUENCE_ANCESTOR_ID: ${{ secrets.CONFLUENCE_ANCESTOR_ID }}
          WRIKE_BASE_URL: ${{ secrets.WRIKE_BASE_URL }}
          WRIKE_TOKEN: ${{ secrets.WRIKE_TOKEN }}
          WRIKE_SPACE_ID: ${{ secrets.WRIKE_SPACE_ID }}
          WRIKE_SPRINT_ROOT_URL: ${{ secrets.WRIKE_SPRINT_ROOT_URL }}
        run: go run main.go

